"""
TranslationSystem - Multi-Language Support für Anwendungen
============================================================
Version: 1.0.0 (isoliert aus _LANG)
Quelle: ARC_EntwicklungsschleifeAdvanced/TranslationSystem.py v2.4

VENDORED, UNCHANGED. Do not edit this file to fit HungryCall.
------------------------------------------------------------
Taken verbatim from the author's existing translation system
(.SOFTWARE/CODING/REL_Editor_PythonBox/translator.py) so that both stay
interchangeable and fixes can travel in either direction. HungryCall talks to
it through hungrycall/i18n.py and never calls the Qt-oriented source scanner
(scan_and_update / _find_german_strings): those patterns look for setText and
QLabel, which an HTML interface does not have. The parts that carry this app
are t(), the locales/translations.json format and set_language().

Verwendung:
-----------
from translator import TranslationSystem

translator = TranslationSystem('de')
label.setText(translator.t('Datei öffnen'))
translator.set_language('en')
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Set


class TranslationSystem:
    """Multi-Language Support System v1.0"""

    def __init__(self, default_lang: str = 'de', app_dir: Path = None):
        """
        Initialisiert Translation-System.

        Args:
            default_lang: Standard-Sprache ('de' oder 'en')
            app_dir: Verzeichnis der Anwendung (default: aktuelles Verzeichnis)
        """
        self.current_lang = default_lang

        if app_dir is None:
            app_dir = Path.cwd()
        self.app_dir = Path(app_dir)

        self.translations_file = self.app_dir / "locales" / "translations.json"

        self.string_patterns = [
            re.compile(r'setText\s*\(\s*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'setWindowTitle\s*\(\s*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'QLabel\s*\(\s*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'QPushButton\s*\(\s*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'addAction\s*\([^,]*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'addTab\s*\([^,]+,\s*["\']([^"\']+)["\']\s*\)'),
            re.compile(r'text\s*=\s*"([^"]+)"'),
        ]

        self.german_hints = [
            "datei", "bearbeiten", "ansicht", "hilfe", "öffnen", "speichern",
            "schließen", "einstellungen", "abbrechen", "ok", "ja", "nein",
            "start", "stop", "pause", "fortsetzen", "laden", "aktualisieren",
            "filter", "fehler", "export", "import", "optionen", "anzeigen",
        ]

        self.translations = {}
        self._load_translations()

    def _load_translations(self):
        if self.translations_file.exists():
            try:
                with open(self.translations_file, 'r', encoding='utf-8') as f:
                    self.translations = json.load(f)
            except Exception:
                self.translations = {}
        else:
            self.translations = {}

    def _save_translations(self):
        self.translations_file.parent.mkdir(parents=True, exist_ok=True)
        # BUG-U4: atomar (tmp + Path.replace) — kein Datenverlust bei Absturz mid-write
        tmp = self.translations_file.with_suffix(self.translations_file.suffix + ".tmp")
        with open(tmp, 'w', encoding='utf-8') as f:
            json.dump(self.translations, f, indent=2, ensure_ascii=False)
        tmp.replace(self.translations_file)

    def t(self, key: str) -> str:
        """
        Übersetzt einen Key in die aktuelle Sprache.

        Args:
            key: Translation-Key (oft der deutsche Originaltext)

        Returns:
            Übersetzter Text oder Key als Fallback
        """
        if not isinstance(key, str) or not key:
            return key if key is not None else ""

        if key in self.translations:
            val = self.translations[key].get(self.current_lang)
            return val if val else (self.translations[key].get("de") or key)

        if self._is_german(key):
            self.translations[key] = {"de": key, "en": ""}
            self._save_translations()

        return key

    def set_language(self, lang: str):
        if not isinstance(lang, str):
            return
        lang_code = lang.lower().strip().split('_')[0].split('-')[0]
        if lang_code in ['de', 'en']:
            self.current_lang = lang_code

    def get_language(self) -> str:
        return self.current_lang

    def add_translation(self, key: str, de: str, en: str):
        self.translations[key] = {"de": de, "en": en}
        self._save_translations()

    def scan_and_update(self, project_dir: Path = None) -> Dict:
        """Scannt Projekt-Dateien nach deutschen Strings und aktualisiert translations.json."""
        if project_dir is None:
            project_dir = self.app_dir

        found_strings = self._find_german_strings(project_dir)

        added = []
        for string in sorted(found_strings):
            if string not in self.translations:
                self.translations[string] = {"de": string, "en": ""}
                added.append(string)

        if added:
            self._save_translations()

        missing = [k for k, v in self.translations.items() if not v.get("en")]

        return {'added': added, 'missing': missing, 'total': len(self.translations)}

    def _find_german_strings(self, directory: Path) -> Set[str]:
        german_strings = set()
        skip_dirs = {'build', 'dist', 'venv', '.venv', '__pycache__', 'releases'}

        for py_file in directory.rglob("*.py"):
            if any(folder in py_file.parts for folder in skip_dirs):
                continue
            try:
                with open(py_file, 'r', encoding='utf-8') as f:
                    content = f.read()
            except Exception:
                continue

            for pattern in self.string_patterns:
                for match in pattern.findall(content):
                    if match and self._is_german(match):
                        german_strings.add(match.strip())

        return german_strings

    def _is_german(self, text: str) -> bool:
        if not isinstance(text, str) or not text:
            return False
        # Check for actual German umlauts and ligatures (single characters ä ö ü Ä Ö Ü ß)
        german_chars = 'äöüÄÖÜß'
        if any(ch in text for ch in german_chars):
            return True
        text_lower = text.lower()
        if any(hint in text_lower for hint in self.german_hints):
            return True
        # ASCII umlaut/ligature sequence matching with English false-positive protection
        english_words = {
            'pass', 'class', 'value', 'true', 'message', 'continue', 'issue',
            'blue', 'glue', 'date', 'save', 'page', 'create', 'database', 'image',
            'state', 'case', 'process', 'session', 'success', 'assert', 'address',
            'assign', 'cross', 'glass', 'loss', 'mass', 'press', 'access', 'express',
            'less', 'due', 'fuel', 'guest', 'guess', 'query', 'subsequent', 'unique',
            'rescue', 'avenue', 'statue', 'queue', 'character', 'element', 'variable',
            'instance', 'argument', 'name', 'same', 'make', 'take', 'base', 'safe',
            'place', 'space', 'clear', 'erase', 'update', 'late', 'rate', 'gate',
            'table', 'label', 'disable', 'enable', 'share', 'care', 'scale'
        }
        words = re.findall(r'\b[a-zA-Z]+\b', text_lower)
        if words and all(w in english_words for w in words):
            return False
        german_sequences = ['ae', 'oe', 'ue', 'ss', 'Ae', 'Oe', 'Ue']
        for seq in german_sequences:
            if seq in text:
                # Ensure the containing word isn't a plain English word
                for word in words:
                    if seq.lower() in word and word not in english_words:
                        return True
        return False

    def get_missing_translations(self) -> List[str]:
        return [k for k, v in self.translations.items() if not v.get("en")]


if __name__ == "__main__":
    tr = TranslationSystem('de')
    print(f"Sprache: {tr.get_language()}")
    result = tr.scan_and_update()
    print(f"Scan: {result['total']} Strings, {len(result['added'])} neu, {len(result['missing'])} ohne EN")
